import type { Metadata } from "next";
import Link from "next/link";
import { MediaFrame } from "@/components/editorial/MediaFrame";
import { PageContainer, SectionLabel } from "@/components/layout/PageContainer";
import { redClayAssets } from "@/lib/assets/registry";

export const metadata: Metadata = { title: "About Red Clay", description: "The material thesis behind Red Clay coffee, place, vessel, and ritual." };

export default function AboutPage() {
  return <main id="main-content" className="about-page">
    <section className="about-opening page-container"><div><SectionLabel>WHAT RED CLAY IS</SectionLabel><h1>A coffee house built around the material character of place.</h1></div><div className="about-opening-copy"><SectionLabel>WHY THE NAME</SectionLabel><p>The earth underfoot. The fired vessel in your hand. Red Clay follows that relationship through coffee, material, and the quiet ritual of making a cup.</p></div></section>
    <section className="about-continuum" aria-labelledby="about-continuum-title"><PageContainer><div className="about-continuum-heading"><SectionLabel>THE CONTINUUM</SectionLabel><h2 id="about-continuum-title">How the Red Clay world connects.</h2></div><ol className="about-continuum-list"><li><span className="about-continuum-number">01</span><h3>Earth</h3><p>Laterite, basalt, linen, shadow.</p></li><li><span className="about-continuum-connector" aria-hidden="true">→</span><span className="about-continuum-number">02</span><h3>Coffee</h3><p>Place, process, and sensory clarity.</p></li><li><span className="about-continuum-connector" aria-hidden="true">→</span><span className="about-continuum-number">03</span><h3>Vessel</h3><p>One companion object, kept secondary to coffee.</p></li><li><span className="about-continuum-connector" aria-hidden="true">→</span><span className="about-continuum-number">04</span><h3>Ritual</h3><p>The stillness of early light.</p></li></ol></PageContainer></section>
    <section className="about-origins page-container"><div className="about-origins-copy"><SectionLabel>WHY EAST AFRICAN ORIGINS</SectionLabel><h2>Three regions, each held at its own distance.</h2><p>Red Clay’s launch world is built around Central Kenya, Kayanza / Burundi, and Southern Ethiopia. They are not a single visual shorthand; each arrives through its own place, process, and record.</p><Link className="editorial-link" href="/origins">Explore the origins <span aria-hidden="true">↗</span></Link></div><MediaFrame asset={redClayAssets.origins.kenyaProcess} className="about-origins-media" sizes="(max-width: 767px) 100vw, 56vw" /></section>
    <section className="about-agency"><PageContainer><div className="about-agency-grid"><div><SectionLabel>REPRESENTATION / AGENCY</SectionLabel><h2>Agricultural expertise, not charity framing.</h2></div><p>People and process imagery should communicate contemporary dignity, work, and agency. Red Clay does not assign fictional identities, interviews, or supplier relationships to the people shown.</p></div></PageContainer></section>
    <section className="about-materials page-container"><div className="about-materials-copy"><SectionLabel>MATERIAL / DESIGN</SectionLabel><h2>The world around the cup is quiet, tactile, and useful.</h2><p>Laterite, basalt, linen, paper, terracotta, coffee, morning light, and shadow give the brand its material language.</p></div><div className="about-materials-media"><MediaFrame asset={redClayAssets.materials.clay} className="about-materials-clay" sizes="(max-width: 767px) 100vw, 42vw" /><MediaFrame asset={redClayAssets.materials.linen} className="about-materials-linen" sizes="(max-width: 767px) 70vw, 24vw" /></div></section>
    <section className="about-roasting"><PageContainer><SectionLabel>COFFEE / ROASTING PHILOSOPHY</SectionLabel><h2>Clarity before spectacle.</h2><p>Red Clay’s coffee language stays close to what can be tasted and seen: place, process, sweetness, structure, and the calm of a well-made cup.</p></PageContainer></section>
    <section className="about-closing page-container"><SectionLabel>CLOSING STATEMENT</SectionLabel><h2>Coffee for the stillness of early light.</h2><Link className="editorial-link" href="/shop">Explore the current harvest <span aria-hidden="true">↗</span></Link></section>
  </main>;
}
