import type { Metadata } from "next";
import Link from "next/link";
import { MediaFrame } from "@/components/editorial/MediaFrame";
import { PageContainer, SectionLabel } from "@/components/layout/PageContainer";
import { redClayAssets } from "@/lib/assets/registry";

export const metadata: Metadata = { title: "About", description: "Red Clay is a contemporary African coffee house built around coffee, place, and thoughtful hospitality." };

export default function AboutPage() {
  return <main id="main-content" className="about-page">
    <section className="about-opening page-container"><div><SectionLabel>WHAT RED CLAY IS</SectionLabel><h1>A coffee house built around the material character of place.</h1></div><div className="about-opening-copy"><SectionLabel>WHY THE NAME</SectionLabel><p>The earth underfoot and the fired vessel in your hand. Red Clay follows the connection between coffee, place, and the cup used to drink it.</p></div></section>
    <section className="about-continuum" aria-labelledby="about-continuum-title"><PageContainer><div className="about-continuum-heading"><SectionLabel>THE CONTINUUM</SectionLabel><h2 id="about-continuum-title">Earth → Coffee → Vessel → Ritual</h2></div><ol className="about-continuum-list"><li><span className="about-continuum-number">01</span><h3>Earth</h3><p>The conditions and knowledge behind a coffee.</p></li><li><span className="about-continuum-connector" aria-hidden="true">→</span><span className="about-continuum-number">02</span><h3>Coffee</h3><p>Specific profiles, seasons, and ways to drink.</p></li><li><span className="about-continuum-connector" aria-hidden="true">→</span><span className="about-continuum-number">03</span><h3>Vessel</h3><p>The Kiln Cup, made to serve coffee.</p></li><li><span className="about-continuum-connector" aria-hidden="true">→</span><span className="about-continuum-number">04</span><h3>Ritual</h3><p>Brewing as a practical, repeatable pleasure.</p></li></ol></PageContainer></section>
    <section className="about-origins page-container"><div className="about-origins-copy"><SectionLabel>WHY EAST AFRICAN ORIGINS</SectionLabel><h2>Three regions, understood on their own terms.</h2><p>Central Kenya, Kayanza / Burundi, and Southern Ethiopia each bring different growing histories, working landscapes, and ways of processing coffee. Origins gives those differences room to be useful.</p><Link className="editorial-link" href="/origins">Explore Origins <span aria-hidden="true">↗</span></Link></div><MediaFrame asset={redClayAssets.origins.kenyaProcess} className="about-origins-media" sizes="(max-width: 767px) 100vw, 56vw" /></section>
    <section className="about-agency"><PageContainer><div className="about-agency-grid"><div><SectionLabel>KNOWLEDGE / WORK</SectionLabel><h2>Coffee is knowledge in practice.</h2></div><p>Growing, selecting, processing, and drying coffee depend on skilled decisions. Red Clay’s origin stories focus on that expertise and on the specific places in which the work happens.</p></div></PageContainer></section>
    <section className="about-materials page-container"><div className="about-materials-copy"><SectionLabel>MATERIAL / DESIGN</SectionLabel><h2>A material language built around coffee.</h2><p>Laterite, basalt, linen, paper, red clay, morning light, and shadow give Red Clay its visual vocabulary. They support the coffee; they do not explain how it tastes.</p></div><div className="about-materials-media"><MediaFrame asset={redClayAssets.materials.clay} className="about-materials-clay" sizes="(max-width: 767px) 100vw, 42vw" /><MediaFrame asset={redClayAssets.materials.linen} className="about-materials-linen" sizes="(max-width: 767px) 70vw, 24vw" /></div></section>
    <section className="about-roasting"><PageContainer><SectionLabel>COFFEE PHILOSOPHY</SectionLabel><h2>Clarity before spectacle.</h2><p>A useful coffee description should help you choose: sweetness, acidity, body, finish, and the references that distinguish one profile from another.</p></PageContainer></section>
    <section className="about-closing page-container"><SectionLabel>CONTINUE</SectionLabel><h2>Coffee for the stillness of early light.</h2><Link className="editorial-link" href="/shop">Shop the harvest <span aria-hidden="true">↗</span></Link></section>
  </main>;
}
